





// Production
### Get all Contacts
GET https://contacts-wdd430.onrender.com/contacts http/1.1

### Get contact by id
GET https://contacts-wdd430.onrender.com/contacts/696283c2f5961f27f8783e26 http/1.1















